### ISSUE TITLE
After creating a project in epicollect.net the Android client crashes

### ISSUE THREAD

**Issue by teleyinex** [ImperialCollegeLondon/EcPlusAndroid#1]
I've created a project called: lichens-pybossa and everytime it tries to load it, the client crashes. The demo project loads well, so I don't know where could be the problem. How can I help with debugging this?

**Comment by daanensen** [comment]
Hi Daniel,

I think it's the hyphen in the project title.  Can you try a project name without the hyphen.

David

**Comment by teleyinex** [comment]
I've just started and caused an error :-) It could be good for you to sanitize the URLs before creating the project :-)
