### ISSUE TITLE
Error reporting feature

### ISSUE THREAD

**Issue by rvcepicollect** [ImperialCollegeLondon/EcPlusAndroid#3]
Hi there,

Any chance an error reporting feature could be added for this app?

There are pre-existing systems that could easily be added to the apk such as the Application Crash Reports for Android (https://github.com/ACRA/acra or http://acra.ch/).

Our EpiCollect+ users at the RVC have encountered numerous crashes of the Android App due to a variety of errors (e.g. incorrect XML files generated by the FormBuilder). 

Unfortunately it has not been possible for a non-technical user to report errors (i.e. more than ".. has stopped unexpectedly"), making it very frustrating on the administrative side to analyse what is happening.

![error2](https://f.cloud.github.com/assets/3265245/243550/6097b606-8a4b-11e2-9da5-865b7240783a.jpg)

Kind regards,
Per Karlsson

Royal Veterinary College

**Comment by mirko77** [comment]
New version has been released at [five.epicollect.net](https://five.epicollect.net)

Please check it out.
