### ISSUE TITLE
fail to load project

### ISSUE THREAD

**Issue by jnozsc** [ImperialCollegeLondon/EcPlusAndroid#5]
Hi Epcollect Staff,

Recently I installed your Android App from Google Play, then I created a project at Epicollect+.

When I tried to load the project, I entered the project name and pressed "load", the app crashed.

How can I debug this issue? Is there any instruction about how to figure out what the problem is?

Thanks

**Comment by mirko77** [comment]
Hi,  could we have the project name and the Android version please?

Thanks

Best,

Mirko

**Comment by jnozsc** [comment]
project name

```
ontodia_text
```

version, well how to check it? I get the latest version from Google Play store, my test mobile model is Samsung Galaxy III

**Comment by daanensen** [comment]
Hi,

It looks like you have not defined a form for your project?

all the best

David

**Comment by jnozsc** [comment]
Thanks, I notice I forget click the "save project" button yesterday.
I click this button today, reload my project from the Android App.
It still does not work, any suggestion? Thanks

**Comment by CIPowell** [comment]
I've just managed to load it onto my S3...

Can you try uninstalling and re-installing EpiCollect+ from the Market?

**Comment by jnozsc** [comment]
sorry for later respond, uninstalling and re-installing works for me. Thanks!
